version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"         # 每天 UTC 时间 3:00 检查
      timezone: "Asia/Shanghai" # 时区设置
    target-branch: "dependabot"
    open-pull-requests-limit: 15  # 最大 PR 数量
    reviewers:                  # 自动添加审阅者
      - "ACANX"
    assignees:                  # 自动分配负责人
      - "ACANX"
    ignore:                    # 忽略特定依赖  
      - dependency-name: "org.springframework:spring-core"
        versions: [">= 7.0.0-"] # 忽略 spring-core 7.x 的更新                    
    commit-message:            # 自定义提交信息
      prefix: "chore"
      include: "scope"
    labels:                    # 自动添加标签
      - "依赖:升级"
      - "自动化:提交"
      - "Dependabot"        
      - "RR"      
    pull-request-branch-name:
      separator: "-"              # 分支名使用短横线分隔
    allow:
      - dependency-type: "all"      # 允许所有依赖类型       
